version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: phonesDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  mobile-management-app:
    build:
      context: .
    container_name: mobile-management-app
    image: mobile-management-app
    ports:
      - "8080:8080"
    networks:
      - mobile-management-network
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/phonesDB
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass

networks:
  mobile-management-network:
    name: mobile-management-network